# Generated by Django 4.2 on 2023-04-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nomeDepartamento', models.CharField(max_length=50)),
                ('caracteristicas', models.CharField(max_length=100)),
            ],
        ),
    ]
